name: wiktionary-ipa-extract build

on:
  # Manual trigger via the GitHub Actions tab
  workflow_dispatch:
  
  # Trigger the build and release of binaries only when Go code changes
  push:
    paths:
      - '**/*.go'  # Trigger when any Go code changes

permissions:
  packages: write
  contents: write

jobs:
  # Job for building binaries (Mac and Linux) and attaching them to the release when Go code changes
  build-and-release-binaries:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Set up Docker container with Golang installed
      - name: Set up Docker
        run: |
          docker pull golang:latest

      # Step 3: Build Linux binary
      - name: Build Linux binary
        run: |
          docker run --name go-build-linux -v ${{ github.workspace }}:/workspace -w /workspace golang:latest /bin/bash -c "go build -o ./wiktionary-ipa-extract-linux cmd/wiktionary-ipa-extract/main.go"

      # Step 4: Build Mac binary
      - name: Build Mac binary
        run: |
          docker run --name go-build-mac -v ${{ github.workspace }}:/workspace -w /workspace golang:latest /bin/bash -c "GOOS=darwin GOARCH=arm64 go build -o ./wiktionary-ipa-extract-mac cmd/wiktionary-ipa-extract/main.go"

      # Step 5: Create GitHub Release (without requiring tags)
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: "auto-release-${{ github.sha }}"  # Automatically generated tag
          name: "Wiktionary IPA Extract Release - ${{ github.sha }}"
          body: "Automated release for commit ${{ github.sha }}"
          draft: false
          prerelease: false
          artifacts: |
            ./wiktionary-ipa-extract-linux
            ./wiktionary-ipa-extract-mac